FROM --platform=linux/amd64 moujikov/ngx_http_qrcode_module:1.0-ngx-1.25.3 AS Module

FROM --platform=linux/amd64 nginx:1.25.3

RUN apt update && apt install -y libqrencode4=4.1.*

COPY --from=Module /ngx_http_qrcode_module.so      /usr/lib/nginx/modules/
COPY examples-nginx/nginx.conf /etc/nginx/
